### PR TITLE
Migrate GitHub Actions to Windows® Server 2019

### PR DESCRIPTION
**Pull request by Cu64**

### CODE REVIEW

**Comment by kowalski7cc** [comment]
Absolutely proprietary

**Comment by Faustino50-Cat** [comment]
> Free Software Philosophy & Other Stuffs
> GitHub (Microsoft)
> Now Windows Server

HTTP 404 - Logic Not Found

**Comment by sticks-stuff** [comment]
but why

**Comment by Cu64** [comment]
Because GNU are bigots and Microsoft employees signed against RMS.

**Comment by Faustino50-Cat** [comment]
So...
Just because Microsoft's employees signed against RMS, it is correct to use their platforms, absolutely **not**-free, to complain about free software topics...?

That does not make any sense.

> Because GNU are bigots and Microsoft employees signed against RMS.

**Pull request closed without merging**
