### PR TITLE
Remove my personal data

### PR DESCRIPTION
**Pull request by ghost**
As I requested in an issue, I would like my personal data removed from this file. Process this request within three months and I won't pursue legal action.

### CODE REVIEW

**Comment by ghost** [comment]
same

**Comment by Technoturnovers** [comment]
@binex-dsk: I recommend you make your own separate issue/pull request so you have a greater chance of being seen

**Comment by ghost** [comment]
ok

**Comment by DanInSpace104** [comment]
@Bronzu your personal data is here again

**Pull request closed without merging**
