### PR TITLE
Make this plugin better

### PR DESCRIPTION
**Pull request by rndtrash**
Снимок экрана от 2021-03-29 00-16-12

### CODE REVIEW

**Comment by mvoolt** [comment]
I approve of these commits and i think they should be merged to the main repository.

**Comment by 0kalekale** [comment]
based

**Comment by SpheeresX** [comment]
Poggers

**Comment by SpheeresX** [comment]
https://github.com/SpheeresX/rms-supporters-are-based

**Comment by rndtrash** [comment]
Hey, you should check out my newer version of the fork which has UserStyle, Cringe and GIGACHAD marks :^)

**Comment by SpheeresX** [comment]
Looks really nice!

**Pull request closed without merging**
