### PR TITLE
Escape github usernames in URI

### PR DESCRIPTION
**Pull request by gretchenfrage**
This script appears to be vulnerable to people injecting malicious code into their personal links. I believe that this code change, which passes the github username through ~~`encodeURIComponent`~~ `encodeURI` (changed following an upstream change), should fix it. However, I am not sure how to run the code in this repo, so I have not tested this change.

### CODE REVIEW

**Comment by midnya** [comment]
You can run the code by enabling and manually running the "workflow" github action on your fork !

**Comment by gretchenfrage** [comment]
Thanks! I am attempting to test now.

**Comment by Bale001** [comment]
Was the issue not fully fixed by #45?

**Comment by gretchenfrage** [comment]
> Was the issue not fully fixed by #45?

Yes, it looks like it was. I realized that in testing just as you responded. 

Closing since the bug is already fixed.

**Comment by gretchenfrage** [comment]
Actually, on second thought, I'm not sure if the vulnerability still exists.

**Comment by augustozanellato** [comment]
> Actually, on second thought, I'm not sure if the vulnerability still exists.

No, it doesn't, calling `encodeURI` is redundant because `url.parse` already url encodes stuff

**Comment by midnya** [comment]
Aren't you the dude who started this in the first place? lmao

**Comment by gretchenfrage** [comment]
Yeah I wanted to double check some things to be sure but it looks like this is patched.

**Pull request closed without merging**
